services:
  - type: web
    plan: free
    name: RishuUserBot
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: ""
    repo: https://github.com/Jodmarmik/dsxuserbot
    branch: main
    envVars:
      - key: SUDO_USERS
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION1
        sync: false
      - key: MONGO_URL
        sync: false
    autoDeploy: false
